# Generated by Django 4.0.3 on 2023-02-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('pelagem', models.CharField(max_length=100, null=True)),
                ('especie', models.CharField(max_length=100, null=True)),
                ('tamanho', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('Macho', 'M'), ('Fêmea', 'F')], max_length=10)),
                ('status', models.CharField(choices=[('Adotado', 'Adotado'), ('Não Adotado', 'Nao_adotado')], max_length=50)),
                ('detalhes', models.TextField(max_length=10000, null=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ONG', to='ONG.ong')),
            ],
        ),
    ]
