# Generated by Django 4.0.3 on 2023-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animal_sexo_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/animal/'),
        ),
    ]
