# Generated by Django 4.0.3 on 2023-03-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='detalhes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/imagens/animal/'),
        ),
    ]
