# Generated by Django 4.0.3 on 2023-03-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_animal_detalhes_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/animal/'),
        ),
    ]
