# Generated by Django 4.0.3 on 2023-03-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(null=True, upload_to='uploads/animal/'),
        ),
    ]
