# Generated by Django 4.0.3 on 2023-04-25 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('UF', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/imagens/ong/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
