# Generated by Django 4.0.3 on 2023-04-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ONG',
        ),
    ]
