# Generated by Django 4.0.3 on 2023-04-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('ONG', '0005_alter_ong_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0005_alter_usuario_imagem'),
        ('user', '0006_rename_usuario_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CostumUser',
        ),
    ]
