# Generated by Django 4.0.3 on 2023-04-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0005_alter_usuario_imagem'),
        ('ONG', '0006_alter_ong_user'),
        ('user', '0007_rename_user_costumuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostumUser',
            new_name='Usuario',
        ),
    ]
