# Generated by Django 4.0.3 on 2023-05-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_costumuser_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
