# Generated by Django 4.0.3 on 2023-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='choose_ong',
            field=models.BooleanField(default=False, verbose_name='ong'),
        ),
    ]
