# Generated by Django 4.0.3 on 2023-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/ong/'),
        ),
    ]
