# Generated by Django 4.0.3 on 2023-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0003_alter_ong_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/ong/'),
        ),
    ]
