# Generated by Django 4.0.3 on 2023-04-25 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ONG', '0004_alter_ong_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
